# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160228_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='datetime',
        ),
        migrations.AddField(
            model_name='vote',
            name='begin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vote',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='homepagenew',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
